# Numpy - Python Data Science Handbook

### Importando Numpy

In [1]:
import numpy as np

### Crear arrays con listas de Python:

In [2]:
lista = [1, 4, 2, 5, 3]
np.array(lista)

array([1, 4, 2, 5, 3])

### Especificando el tipo de dato de los elementos del array:

In [3]:
np.array([1, 2, 3, 4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

### Arrays multi dimensionales - nested lists.

In [4]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Crear arrays desde Numpy

#### np.zeros
Crea un array donde todos los elementos son 0 (ceros)

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### np.ones
Crea un array donde todos los elementos son 1 (unos)

In [6]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### np.full 
Crea un array donde todos sus valores son un valor específico dado

In [7]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

#### np.arange
Crea un array con valores de un rango dado (de la forma $[a,b)$ )

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### np.linspace
Crea un array de valores distribuidos uniformemente entre dos dados. (de la forma $[a,b]$ )

In [9]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

#### np.random.random
Crea un array de tamaño dado con valores aleatorios entre 0 y 1.

In [10]:
np.random.random(3)

array([0.16277272, 0.1364587 , 0.42561445])

In [11]:
np.random.random((5,2))

array([[0.61955911, 0.49283285],
       [0.03810794, 0.76682083],
       [0.3088337 , 0.25112081],
       [0.28167745, 0.93276546],
       [0.15597695, 0.46305175]])

#### np.random.normal
Crea un array con valores que siguen una DISTRIBUCIÓN NORMAL, con MEDIA = 0 y DESVIACIÓN ESTÁNDAR = 1.

In [12]:
np.random.normal(0,1, (2,2))

array([[ 1.30189329,  1.10044776],
       [-0.57069416, -0.61423448]])

In [13]:
np.random.normal(-5, 15, (1,3))

array([[-30.43061986,   3.50716182,  10.24436712]])

#### np.random.randint
Crea un array de valores enteros entre dos valores dados.

In [14]:
np.random.randint(0, 10, (2,2))

array([[8, 3],
       [8, 4]])

#### np.eye
Crea una matriz identidad

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.empty
Crea un array de cualquier tipo de valor.

In [16]:
np.empty(3)

array([30.43061986,  3.50716182, 10.24436712])

### Atributos de los numpy arrays

#### Atributo "ndim"
Es el número de dimensiones del array

In [17]:
np.array([1, 2, 3, 4]).ndim

1

In [18]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]).ndim

2

#### Atributo "shape"
Es el tamaño del array

In [19]:
np.array([1, 2, 3, 4]).shape

(4,)

In [20]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]).shape

(3, 4)

#### Atributo "size"
Es el tamaño total del array.

Ejemplo:
Si shape = (2,2) --> size = 2 x 2 = 4

In [21]:
# El resultado debería ser 3 (cantidad de filas) x 4 (cantidad de columnas) = 12.

np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]).size

12

#### Atributo "itemsize"
Cantidad de bytes de los elementos del array

In [22]:
np.array([3.3, 5.2, 9]).itemsize

8

#### Atributo "nbytes"
Cantidad de bytes total del array

nbytes = itemsize x size.

In [23]:
np.array([3.3, 5.2, 9]).nbytes

24

### Array Indexing

In [24]:
# Array de 1 dimensión

array_dimension1 = np.array([1, 3, 5, 9, 15, 21])

## Ejemplo 1:
print(array_dimension1[2])

## Ejemplo 2:
print(array_dimension1[-2])

5
15


In [25]:
# Array de 2 dimensiones:

array_dimension2 = np.array([[1, 3, 5], [9, 15, 21]])

## Ejemplo 1: 
print(array_dimension2[1,1])

## Ejemplo 2:
print(array_dimension2[-1,-3])

15
9


### Array slicing

Es de la forma x[start:stop:step]

#### Array de 1 dimensión

In [27]:
array_slicing1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Ejemplo 1:
print(array_slicing1[:5])

# Ejemplo 2:
print(array_slicing1[5:])

# Ejemplo 3: 
print(array_slicing1[4:7])

# Ejemplo 4:
print(array_slicing1[::2])

# Ejemplo 5:
print(array_slicing1[1::2])

## Usando "-STEP", damos vuelta el array:

print(array_slicing1[::-1])

print(array_slicing1[5::-2])

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


#### Array de 2 dimensiones

In [31]:
array_slicing2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])

# Ejemplo 1
print(array_slicing2[:2, :3])

# Ejemplo 2
print(array_slicing2[:, ::2])

# Ejemplo 3
print(array_slicing2[:, 0])

# Ejemplo 4
print(array_slicing2[0, :])

# Usando "-STEP" para dar vuelta el array (array traspuesto)
print(array_slicing2[::-1, ::-1])


[[12  5  2]
 [ 7  6  8]]
[[12  2]
 [ 7  8]
 [ 1  7]]
[12  7  1]
[12  5  2  4]
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]


### Copiar arrays

Usar el método .copy()

<b>NO</b> usar bracket notation, porque modificamos el array original

In [33]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

copia = original[:2, :2].copy()

# Si modificamos copia, con original no sucede nada:

copia[1,1] = 9
print(copia)
print(original)

[[1 2]
 [4 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Concatenar arrays

#### Con .concatenate()

In [35]:
# Arrays de una dimensión

m = np.array([1, 2, 3])
n = np.array([4, 5, 6])
o = np.concatenate([m, n])

In [36]:
o

array([1, 2, 3, 4, 5, 6])

In [39]:
# Arrays de dos dimensiones

grid_1 = np.array([[1, 2, 3], [4, 5, 6]])
grid_2 = np.array([[7, 8, 9]])

grid_1y2 = np.concatenate([grid_1, grid_2], axis=0) # Axis 0, concatenate agregando filas

In [40]:
grid_1y2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
grid_3 = np.array([[7, 8, 9], [10, 11, 12]])

grid_1y3 = np.concatenate([grid_1, grid_3], axis=1) # Axis 1, concatena agregando columnas

In [42]:
grid_1y3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### Con .vstack(), .hstack() y .dstack()

In [43]:
# Usando .vstack()

a = np.array([1, 2, 3])
b = np.array([[9, 8, 7], [6, 5, 4]])

c = np.vstack([a, b])

In [44]:
c

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [45]:
# Usando hstack
d = np.array([[10], [11]])

e = np.hstack([b, d])

In [46]:
e

array([[ 9,  8,  7, 10],
       [ 6,  5,  4, 11]])

### Splitting of arrays

#### Con .split()

In [55]:
ejemplo_split = np.array([1, 2, 3, 4, 5, 6])

split1, split2 = np.split(ejemplo_split, 2)

In [56]:
split1

array([1, 2, 3])

In [57]:
split2

array([4, 5, 6])

### U-Func

In [72]:
"""
# BÁSICAS

Suma (+) -- np.add
Resta (-) -- np.subtract
Negación (-) -- np.negative
Multiplicación (*) -- np.multiply
División (/) -- np.divide
División entera (//) -- np.floor_divide
Potencia (**) -- np.power
Resto (%) -- np.mod

# VALOR ABSOLUTO: np.absolute / np.abs

# FUNCIONES TRIGONOMÉTRICAS
Número Pi -- np.pi
Seno -- np.sin
Coseno -- np.cos
Tangente -- np.tan
Arco seno -- np.arcsin
Arco coseno -- np.arccos
Arco tangente -- np.arctan

# FUNCIONES EXPONENCIALES Y LOGARÍTMICAS
e^x -- np.exp(x)
2^x -- np.exp2(x)
3^x -- np.exp(3, x)
ln(x) -- np.log(x)
log2(x) -- np.log2(x)
log10(x) -- np.log10(x)

# OTRAS FUNCIONES (ESTADÍSTICA, SUMATORIAS Y PRODUCTORIAS)
np.sum
np.prod
np.mean
np.std
np.var
np.argmin
np.argmax
np.median
np.percentile
np.any
np.all

"""

'\n# BÁSICAS\n\nSuma (+) -- np.add\nResta (-) -- np.subtract\nNegación (-) -- np.negative\nMultiplicación (*) -- np.multiply\nDivisión (/) -- np.divide\nDivisión entera (//) -- np.floor_divide\nPotencia (**) -- np.power\nResto (%) -- np.mod\n\n# VALOR ABSOLUTO: np.absolute / np.abs\n\n# FUNCIONES TRIGONOMÉTRICAS\nNúmero Pi -- np.pi\nSeno -- np.sin\nCoseno -- np.cos\nTangente -- np.tan\nArco seno -- np.arcsin\nArco coseno -- np.arccos\nArco tangente -- np.arctan\n\n# FUNCIONES EXPONENCIALES Y LOGARÍTMICAS\ne^x -- np.exp(x)\n2^x -- np.exp2(x)\n3^x -- np.exp(3, x)\nln(x) -- np.log(x)\nlog2(x) -- np.log2(x)\nlog10(x) -- np.log10(x)\n\n# OTRAS FUNCIONES (ESTADÍSTICA, SUMATORIAS Y PRODUCTORIAS)\nnp.sum\nnp.prod\nnp.mean\nnp.std\nnp.var\nnp.argmin\nnp.argmax\nnp.median\nnp.percentile\nnp.any\nnp.all\n\n'

#### Aggregates

In [60]:
# Ejemplo 1:
array1 = np.arange(1, 6)
suma_red = np.add.reduce(x) # Equivalente a hacer la sumatoria entre 1 y 6 de x.

print(suma_red)

15


In [63]:
# Ejemplo 2
mult_red = np.multiply.reduce(array1) # Equivalente a hacer la productoria entre 1 y 5 de x

print(mult_red)

120


In [64]:
# Ejemplo 3:
suma_acum = np.add.accumulate(array1)

suma_acum

array([ 1,  3,  6, 10, 15], dtype=int32)

### Aggregations

In [66]:
# np.min -- mínimo de un array
# np.max -- máximo de un array

array_ej = np.array([3, 5, 9, 3, 21, 4, -10])

In [67]:
np.min(array_ej)

-10

In [68]:
np.max(array_ej)

21

In [69]:
# En arrays multidimensionales:
array_2d = np.array([[1, 4, -10], [9, -5, 19]])

In [70]:
np.min(array_2d, axis=0) #Mínimo de cada columna

array([  1,  -5, -10])

In [71]:
np.max(array_2d, axis=1) #Máximo de cada fila

array([ 4, 19])

### Lógica booleana en arrays de Numpy

In [75]:
x_logica = np.array([1, 2, 3, 4, 5])

x_logica <= 3

array([ True,  True,  True, False, False])

In [76]:
# Varias condiciones:
x_logica * 2 == x_logica ** 2

array([False,  True, False, False, False])

In [77]:
# Usando np.any() y np.all()

np.any(x_logica >= 5)

True

In [78]:
np.all(x_logica == 2)

False

In [79]:
# Realizando operaciones usando operadores booleanos (disyunción, conjunción, negación y disyunción exclusiva)

np.sum((x_logica > 3) & (x_logica <=5))

2

### Ordenando arrays:

In [80]:
ordenar_ej = np.array([2, 1, 4, 3, 5])

#### Con el método .sort()

In [81]:
ordenar_ej.sort()

In [82]:
ordenar_ej

array([1, 2, 3, 4, 5])

#### Con el método .argsort()

In [85]:
ordenar_ej2 = np.array([5, 21, 12, 9, 8, -3, -40])

ordenar_argsort = np.argsort(ordenar_ej2)

In [86]:
ordenar_argsort

array([6, 5, 0, 4, 3, 2, 1], dtype=int32)

#### Ordenando por columnas

In [87]:
ordenar_2d = np.array([[6, 3, 7, 4, 6, 9], [2, 6, 7, 4, 3, 7], [7, 2, 5, 4, 1, 7], [5, 1, 4, 0, 9, 5]])

In [89]:
np.sort(ordenar_2d, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

#### Ordenando por filas

In [90]:
np.sort(ordenar_2d, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])